# Importing necessary libraries

In [1]:
import pandas as pd
import datetime as dt
import yfinance as yf

# Data Collection

In [2]:
symbol='AXISBANK.NS'
start=dt.datetime(2021,7,1)
end=dt.datetime(2022,1,28)
stk_data=yf.download(symbol,start=start,end=end)

[*********************100%%**********************]  1 of 1 completed

In [3]:
stk_data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-07-01,750.000000,754.400024,744.500000,746.450012,744.555725,5695690
2021-07-02,747.599976,752.849976,744.000000,750.650024,748.745117,3557647
2021-07-05,757.099976,762.000000,753.400024,760.349976,758.420410,4680089
2021-07-06,757.000000,767.000000,755.200012,758.349976,756.425476,5529485
2021-07-07,755.900024,764.000000,752.250000,762.900024,760.963989,3573368
...,...,...,...,...,...,...
2022-01-20,731.049988,737.150024,722.150024,728.900024,727.050232,8505400
2022-01-21,722.000000,725.250000,708.049988,712.500000,710.691895,10689060
2022-01-24,715.000000,716.400024,688.200012,704.599976,702.811890,8812501
2022-01-25,714.000000,755.000000,708.599976,752.200012,750.291138,38088158
2022-01-27,744.000000,777.000000,738.099976,773.849976,771.886169,34927774

In [4]:
stk_data=stk_data[["Open","High","Low","Close"]]

In [5]:
stk_data

                  Open        High         Low       Close
Date
2021-07-01  750.000000  754.400024  744.500000  746.450012
2021-07-02  747.599976  752.849976  744.000000  750.650024
2021-07-05  757.099976  762.000000  753.400024  760.349976
2021-07-06  757.000000  767.000000  755.200012  758.349976
2021-07-07  755.900024  764.000000  752.250000  762.900024
...                ...         ...         ...         ...
2022-01-20  731.049988  737.150024  722.150024  728.900024
2022-01-21  722.000000  725.250000  708.049988  712.500000
2022-01-24  715.000000  716.400024  688.200012  704.599976
2022-01-25  714.000000  755.000000  708.599976  752.200012
2022-01-27  744.000000  777.000000  738.099976  773.849976

[144 rows x 4 columns]

# Data Preprocessing

In [23]:

from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
data1=ms.fit_transform(stk_data)
print("Length : ",data1.shape)

Length :  (144, 4)

In [26]:
data1

array([[0.50898197, 0.44154881, 0.54381512, 0.49149503],
       [0.49700581, 0.43385435, 0.54099743, 0.51314458],
       [0.54441099, 0.47927516, 0.59397023, 0.56314433],
       [0.54391211, 0.50409522, 0.60411386, 0.55283505],
       [0.53842321, 0.48920319, 0.58748939, 0.57628891],
       [0.55888217, 0.50483994, 0.58439   , 0.53247448],
       [0.51896201, 0.43410279, 0.51986471, 0.49613402],
       [0.52145702, 0.45842626, 0.56522953, 0.52835052],
       [0.55389215, 0.53387928, 0.60298672, 0.6167527 ],
       [0.61352294, 0.53611315, 0.65370522, 0.61314439],
       [0.61127737, 0.55994034, 0.6677937 , 0.6342786 ],
       [0.63872248, 0.54877131, 0.6680754 , 0.61881468],
       [0.52045896, 0.50235794, 0.57255547, 0.53659813],
       [0.53393207, 0.44551995, 0.54212457, 0.48788672],
       [0.50948085, 0.46190113, 0.52409126, 0.49304136],
       [0.50399195, 0.48920319, 0.51901927, 0.53762912],
       [0.52894205, 0.46934714, 0.54663282, 0.5422681 ],
       [0.51147698, 0.4494911 , 0.45702998, 0.41546411],
       [0.43313362, 0.34425402, 0.36122835, 0.37010334],
       [0.35928139, 0.31298081, 0.38320651, 0.34097951],
       [0.34955079, 0.26408543, 0.33333345, 0.2979384 ],
       [0.3343313 , 0.29833692, 0.36066495, 0.36108273],
       [0.37924147, 0.37428622, 0.40180323, 0.45103093],
       [0.46157679, 0.45445511, 0.51084823, 0.52938151],
       [0.52395203, 0.44452709, 0.53817973, 0.50618563],
       [0.49401192, 0.45768184, 0.51169333, 0.46262887],
       [0.4640718 , 0.45644084, 0.51704702, 0.53814446],
       [0.53642708, 0.48920319, 0.60298672, 0.56932996],
       [0.58383226, 0.51402324, 0.58889824, 0.56546398],
       [0.55389215, 0.4862249 , 0.59368818, 0.54768041],
       [0.54640712, 0.49168519, 0.59847847, 0.56082499],
       [0.53892209, 0.49813834, 0.60862211, 0.57164961],
       [0.55389215, 0.46934714, 0.57086492, 0.54458775],
       [0.57784418, 0.48821032, 0.57762746, 0.53247448],
       [0.48802383, 0.41474303, 0.49704145, 0.45953621],
       [0.50648696, 0.41722503, 0.48689782, 0.43814433],
       [0.4391217 , 0.41821789, 0.47055505, 0.49097938],
       [0.5       , 0.42690491, 0.49140606, 0.45335058],
       [0.42964054, 0.41970704, 0.475345  , 0.49097938],
       [0.49151691, 0.46736142, 0.52409126, 0.5221652 ],
       [0.53892209, 0.61578546, 0.59735133, 0.68530934],
       [0.68313377, 0.61330345, 0.73485498, 0.69793827],
       [0.74900178, 0.76222377, 0.8306566 , 0.76185592],
       [0.73602785, 0.69818791, 0.81375043, 0.78144349],
       [0.78093803, 0.71705139, 0.78726403, 0.75721662],
       [0.76272434, 0.69719535, 0.83037456, 0.77164955],
       [0.7485029 , 0.66492928, 0.75542394, 0.70489691],
       [0.70858275, 0.65475282, 0.76077763, 0.74020637],
       [0.70359273, 0.63663436, 0.76754017, 0.71675283],
       [0.68862267, 0.62050133, 0.76359533, 0.70747423],
       [0.71357277, 0.67287158, 0.80022536, 0.73866005],
       [0.73852286, 0.6552494 , 0.78331919, 0.72319613],
       [0.7210578 , 0.70488951, 0.79515337, 0.78092784],
       [0.80264449, 0.77066265, 0.84108194, 0.80541237],
       [0.75848294, 0.7103498 , 0.80867845, 0.74613402],
       [0.73478035, 0.66294356, 0.70047889, 0.7435567 ],
       [0.7210578 , 0.65202267, 0.7776838 , 0.70747423],
       [0.73028921, 0.73988572, 0.81459554, 0.83015489],
       [0.82110762, 0.75204761, 0.82896571, 0.75747429],
       [0.77295412, 0.7115908 , 0.81600438, 0.75180431],
       [0.76846298, 0.69570591, 0.73260068, 0.71185586],
       [0.67365261, 0.61578546, 0.73541838, 0.67551572],
       [0.65818367, 0.60511271, 0.65849517, 0.59510316],
       [0.57584836, 0.52742613, 0.59735133, 0.60335077],
       [0.61427126, 0.57433609, 0.68920811, 0.65927848],
       [0.63073857, 0.5884834 , 0.6942801 , 0.67783505],
       [0.6699101 , 0.63911637, 0.7213299 , 0.65902081],
       [0.70858275, 0.61901218, 0.71062252, 0.64948454],
       [0.66816371, 0.59344741, 0.7213299 , 0.67448472],
       [0.66866259, 0.63315949, 0.73823607, 0.70128891],
       [0.69860271, 0.66641843, 0.77458441, 0.7528353 ],
       [0.7582335 , 0.69024562, 0.81825868, 0.73969072],
       [0.75349292, 0.68776361, 0.78895458, 0.77809285],
       [0.85828333, 0.76718778, 0.86813174, 0.83608254],
       [0.85828333, 0.80193586, 0.84812617, 0.77603118],
       [0.76147683, 0.73641085, 0.81149614, 0.7922681 ],
       [0.79815366, 0.73492171, 0.81318669, 0.80773202],
       [0.81836317, 0.79200783, 0.89489984, 0.85360844],
       [0.9086824 , 1.        , 1.        , 1.        ],
       [1.        , 0.92429884, 0.98901092, 0.98350541],
       [0.95808372, 0.87043914, 0.77571155, 0.70309291],
       [0.6961077 , 0.61330345, 0.60101447, 0.55283505],
       [0.56886221, 0.47927516, 0.37193573, 0.46855683],
       [0.53393207, 0.46934714, 0.51845587, 0.52190722],
       [0.52145702, 0.47604844, 0.56382069, 0.53994845],
       [0.55613772, 0.48250189, 0.56635668, 0.5128866 ],
       [0.54391211, 0.45470325, 0.58269945, 0.52500019],
       [0.56387219, 0.47431115, 0.52690895, 0.51520625],
       [0.50898197, 0.43931494, 0.53733429, 0.48427841],
       [0.47255489, 0.43633635, 0.47337275, 0.5064433 ],
       [0.49900194, 0.40977902, 0.49084232, 0.44819594],
       [0.47305377, 0.3839661 , 0.48182583, 0.43788666],
       [0.44910174, 0.38992297, 0.45083119, 0.42345373],
       [0.42539915, 0.336808  , 0.41307401, 0.38685592],
       [0.36427141, 0.29511049, 0.33107915, 0.31572165],
       [0.3343313 , 0.25093068, 0.30374765, 0.28479381],
       [0.32435126, 0.23603864, 0.1656806 , 0.18195901],
       [0.16467064, 0.13502115, 0.16539855, 0.17809304],
       [0.20958081, 0.14718273, 0.19188496, 0.17551572],
       [0.18962074, 0.10697437, 0.16089031, 0.14845386],
       [0.10479041, 0.04690996, 0.07016067, 0.05489703],
       [0.08507977, 0.        , 0.00760764, 0.        ],
       [0.        , 0.05956813, 0.        , 0.02345386],
       [0.08433145, 0.07917603, 0.06762468, 0.14690722],
       [0.13473052, 0.06626942, 0.1129895 , 0.12886598],
       [0.15518948, 0.10871165, 0.12961397, 0.11288672],
       [0.1297405 , 0.06602128, 0.07410551, 0.06185567],
       [0.11976046, 0.12956056, 0.12397858, 0.18505167],
       [0.23453091, 0.17920066, 0.22344335, 0.2371134 ],
       [0.25024959, 0.17101023, 0.22541559, 0.22087648],
       [0.21007969, 0.13154628, 0.20146519, 0.19046398],
       [0.25449099, 0.23057835, 0.25415595, 0.27268054],
       [0.26447103, 0.24100266, 0.2795152 , 0.30824767],
       [0.32135737, 0.27078672, 0.3355874 , 0.31649497],
       [0.35429137, 0.2804666 , 0.32149892, 0.30180438],
       [0.29690615, 0.21121859, 0.20907283, 0.19484561],
       [0.1644212 , 0.08140959, 0.06818808, 0.11984536],
       [0.17465068, 0.08711833, 0.08171315, 0.07603093],
       [0.10978043, 0.05658954, 0.09016624, 0.09407216],
       [0.14471056, 0.09456434, 0.13863045, 0.14278357],
       [0.16541926, 0.08215432, 0.08143145, 0.08453621],
       [0.07509973, 0.04542052, 0.04480142, 0.10850541],
       [0.14620751, 0.07644558, 0.13524936, 0.12551565],
       [0.13223551, 0.07024057, 0.10848125, 0.10000013],
       [0.09980039, 0.0379745 , 0.09298393, 0.09149485],
       [0.12450104, 0.10449236, 0.13074111, 0.14149491],
       [0.16092812, 0.16406049, 0.17469709, 0.23324742],
       [0.26447103, 0.22635876, 0.29332197, 0.29922706],
       [0.31886236, 0.32489456, 0.33671454, 0.3907219 ],
       [0.35903195, 0.33780086, 0.40011268, 0.40824749],
       [0.42914166, 0.37453466, 0.43533387, 0.40979381],
       [0.42739528, 0.38992297, 0.48013529, 0.47268048],
       [0.47355296, 0.40506315, 0.50324025, 0.47500013],
       [0.50723559, 0.42690491, 0.53620748, 0.4935567 ],
       [0.50399195, 0.41474303, 0.5018314 , 0.46185586],
       [0.43313362, 0.34996275, 0.38348821, 0.36391771],
       [0.35429137, 0.273765  , 0.34657648, 0.31726829],
       [0.34680634, 0.34971461, 0.37334458, 0.38195895],
       [0.38522955, 0.33010671, 0.39842213, 0.40463918],
       [0.41442105, 0.35591962, 0.4178643 , 0.40103118],
       [0.36926143, 0.29684777, 0.33840509, 0.31649497],
       [0.3343313 , 0.2529164 , 0.22654274, 0.2757732 ],
       [0.32934128, 0.44452709, 0.34150449, 0.52113421],
       [0.47904186, 0.55373532, 0.50774849, 0.63273196]])

# Creating dataframe for processed values

In [27]:
data1=pd.DataFrame(data1,columns=["Open","High","Low","Close"])

In [30]:
data1.shape

(144, 4)

In [8]:
import warnings
warnings.filterwarnings("ignore")

In [9]:
# creating dictionary to store values
performance={"Model":[],"RMSE":[],"MaPe":[],"Lag":[],"Test":[]} 

# creating list
listt=["Close","High","Open","Low"]

In [10]:
print(listt)

['Close', 'High', 'Open', 'Low']

In [11]:
performance

{'Model': [], 'RMSE': [], 'MaPe': [], 'Lag': [], 'Test': []}

In [31]:
datasetTwo=data1[listt]
datasetTwo

        Close      High      Open       Low
0    0.491495  0.441549  0.508982  0.543815
1    0.513145  0.433854  0.497006  0.540997
2    0.563144  0.479275  0.544411  0.593970
3    0.552835  0.504095  0.543912  0.604114
4    0.576289  0.489203  0.538423  0.587489
..        ...       ...       ...       ...
139  0.401031  0.355920  0.414421  0.417864
140  0.316495  0.296848  0.369261  0.338405
141  0.275773  0.252916  0.334331  0.226543
142  0.521134  0.444527  0.329341  0.341504
143  0.632732  0.553735  0.479042  0.507748

[144 rows x 4 columns]

# Train and test Split

In [32]:
test_obs=28
train=datasetTwo[:-test_obs]
test=datasetTwo[-test_obs:]

# Model creation

In [38]:
from statsmodels.tsa.api import VAR
for i in [1,2,3,4,5,6,7,8,9,10]:
    model=VAR(train)
    results=model.fit(i)
    print('Order =', i)
    print('AIC: ', results.aic)
    print('BIC: ', results.bic)
    print()

Order = 1
AIC:  -28.081963557683824
BIC:  -27.60458405709891

Order = 2
AIC:  -28.20291265731209
BIC:  -27.33884998939804

Order = 3
AIC:  -28.051986864437684
BIC:  -26.79690574432227

Order = 4
AIC:  -27.85775303801855
BIC:  -26.207235866160815

Order = 5
AIC:  -27.695836206850036
BIC:  -25.64538091937043

Order = 6
AIC:  -27.590577395204647
BIC:  -25.135595244484268

Order = 7
AIC:  -27.502241924389672
BIC:  -24.638055187338473

Order = 8
AIC:  -27.629101172413858
BIC:  -24.350940783706477

Order = 9
AIC:  -27.500838635138486
BIC:  -23.803841742611738

Order = 10
AIC:  -27.36928781050418
BIC:  -23.24849524980249

# Selecting Order and Forecasting

In [46]:
x = model.select_order(maxlags=12)
order=x.selected_orders["aic"]
result = model.fit(order)  
lagged_Values = train.values[-order:]
pred = result.forecast(y=lagged_Values,steps=28) 
preds=pd.DataFrame(pred,columns=listt)
preds.to_csv("varforecasted_{}.csv".format(test_obs))

In [47]:
preds

       Close      High      Open       Low
0   0.174744  0.151157  0.209677  0.168529
1   0.182568  0.144748  0.195710  0.162636
2   0.191194  0.151601  0.199240  0.186317
3   0.204385  0.163280  0.207529  0.199763
4   0.217197  0.172751  0.219163  0.213565
5   0.228183  0.184389  0.231338  0.227175
6   0.239638  0.194787  0.241761  0.239841
7   0.250976  0.205518  0.252898  0.251789
8   0.261791  0.216091  0.263763  0.263893
9   0.272335  0.226449  0.274253  0.275276
10  0.282481  0.236394  0.284456  0.286197
11  0.292135  0.246016  0.294294  0.296639
12  0.301351  0.255191  0.303661  0.306560
13  0.310118  0.263947  0.312613  0.315965
14  0.318435  0.272279  0.321130  0.324900
15  0.326324  0.280193  0.329215  0.333359
16  0.333799  0.287697  0.336886  0.341368
17  0.340874  0.294811  0.344155  0.348948
18  0.347571  0.301546  0.351038  0.356119
19  0.353905  0.307921  0.357552  0.362900
20  0.359895  0.313952  0.363715  0.369311
21  0.365559  0.319655  0.369543  0.375372
22  0.370912  0.325048  0.375054  0.381100
23  0.375973  0.330146  0.380263  0.386515
24  0.380755  0.334965  0.385187  0.391631
25  0.385275  0.339519  0.389841  0.396466
26  0.389546  0.343823  0.394239  0.401035
27  0.393582  0.347890  0.398395  0.405353

# Evaluation Metrics

In [41]:
from sklearn.metrics import mean_squared_error
rmse= round(mean_squared_error(test,pred,squared=False))

from sklearn.metrics import mean_absolute_percentage_error
mape=mean_absolute_percentage_error(test,pred)

# Appending the values in dictionary

In [42]:
performance["Model"].append(listt)
performance["RMSE"].append(rmse)
performance["MaPe"].append(mape)
performance["Lag"].append(order)
performance["Test"].append(test_obs)
# Converting dictionary into dataframe
perf=pd.DataFrame(performance)

In [43]:
perf

                      Model  RMSE      MaPe  Lag  Test
0  [Close, High, Open, Low]     0  0.595967    2    28